#!/usr/bin/env ansible-playbook

---
- name: basic workstation setup
  hosts: all
  remote_user: root
  gather_facts: false

  roles:
    - wakeup
#    - { role: tdobrovolny.autoupdate }
    - suspend
...
