---

- name check powerstate
  sudo: false
  local_action: command "ping -c 1  {{ ansible_hostname }}"
  register online

- local_action: wake-on-lan 
  when online == 1

- local_action: wait_for port=22 host="{{ ansible_ssh_host | default(inventory_hostname) }}" delay=10 timeout=300
...
