---

- name: check powerstate
  become: false
  local_action: wait_for port=22 host="{{ ansible_hostname | default(inventory_hostname) }}" timeout=3
  register: online
  ignore_errors: True

- name: send magic packet
  become: false
  local_action: wakeonlan mac="{{ wol_mac }}" broadcast="192.168.2.255"
  when: online.failed is defined

- name: wait for client to be online
  become: false
  local_action: wait_for port=22 host="{{ ansible_hostname | default(inventory_hostname) }}" delay=10 timeout=300
  when: online.failed is defined

- name: now gather facts
  setup:

...
