---

#- name: make sure certain system groups exist, even if software is not yet installed
#  group:
#    name: "{{ item.name }}"
#    state: present
#    gid: " {{ item.id }}"
#    system: yes
#
#  with_items:
#   - { name: docker, id: 982 }
#   - { name: vagrant, id: 963 }

- name: add users
  user:
    name: "{{ item.key }}"
    password: "{{ item.value.encpw }}"
    update_password: on_create
    comment: "{{ item.value.gecos }}"
    createhome: yes
    uid: "{{ item.value.uid }}"
    group: "{{ item.value.pgid }}"
    groups: "{{ item.value.ogid }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_type: rsa
    system: no
  with_dict: "{{ workstation_user }}"

##
## TODO: 
#  - Create something to configure backintime
#  - Set USer defaults in /var/lib/AccountsService/users/username
#    [User]
#    Language=
#    XSession=gnome-classic
#    SystemAccount=false
#    
##
