---
# fetch all public hostkeys and store them in hostkey format
# <hostname> <algorithm> <key>

- name: add rsa key to local host
  become: false
  local_action: known_hosts state=present name="{{ ansible_fqdn }}" path=roles/download-ssh-hostkeys/ssh_known_hosts key="{{ ansible_fqdn }},{{ ansible_default_ipv4.address }} ssh-rsa {{ ansible_ssh_host_key_rsa_public }}"
  when: ansible_ssh_host_key_rsa_public is defined

- name: add ed25519 hostkey to local host
  become: false
  local_action: known_hosts state=present name="{{ ansible_fqdn }}" path=roles/download-ssh-hostkeys/ssh_known_hosts key="{{ ansible_fqdn }},{{ ansible_default_ipv4.address }} ssh-ed25519 {{ ansible_ssh_host_key_ed25519_public }}"
  when: ansible_ssh_host_key_ed25519_public is defined

- name: add ecdsa hostkey to local host
  become: false
  local_action: known_hosts state=present name="{{ ansible_fqdn }}" path=roles/download-ssh-hostkeys/ssh_known_hosts key="{{ ansible_fqdn }},{{ ansible_default_ipv4.address }} ecdsa-sha2-nistp256 {{ ansible_ssh_host_key_ecdsa_public }}"
  when: ansible_ssh_host_key_ecdsa_public is defined

