---

- name: Add Google Chrome repository
  yum_repository:
    name: google-chrome
    description: google-chrome
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    enabled: yes
    gpgcheck: yes
    gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub

- name: Add Google Chrome signing key
  rpm_key:
    state: present
    key: https://dl-ssl.google.com/linux/linux_signing_key.pub

- name: Enable UnitedRPMs for Multimedia
  dnf:
    name: https://raw.githubusercontent.com/UnitedRPMs/unitedrpms/master/RPM/unitedrpms-25-1.noarch.rpm
    state: present

- name: Add UnitedRPMs signing key
  rpm_key:
    state: present
    key: https://raw.githubusercontent.com/UnitedRPMs/unitedrpms.github.io/master/URPMS-GPG-PUBLICKEY-Fedora-25


- name: Disable RPM Fusion directories
  dnf:
    name: "{{ item }}"
    state: absent
  with_items:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_lsb.release }}.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_lsb.release }}.noarch.rpm

- name: Enable copr Repositories
  shell: |
   if grep -q "^enabled=1$" "/etc/yum.repos.d/_copr_{{ item.name }}-{{ item.project }}.repo"; then
      exit 90
   else
      dnf -y copr enable "{{ item.name }}/{{ item.project }}"
   fi
  with_items:
    - { name: 'sergiomb', project: 'google-drive-ocamlfuse' }
  register: copr_enabled
  changed_when: copr_enabled.rc == 0
  failed_when: copr_enabled.rc > 0 and copr_enabled.rc != 90
  tags:
    - coprrepo

- name: Disable Samsung ULD repo - is in United ( http://negativo17.org/samsung-unified-linux-driver-printers-scanners/ )
  shell: |
   if [ -f /etc/yum.repos.d/fedora-uld.repo ]; then
      echo ULD repo is enabled, remove it
      rm -f /etc/yum.repos.d/fedora-uld.repo
      exit 90
   else
      echo "Repo is not enabled"
      echo 0
      #dnf config-manager --add-repo=http://negativo17.org/repos/fedora-uld.repo
   fi
  register: samsungrepo
  changed_when: samsungrepo.rc == 90
  failed_when: samsungrepo.rc > 0 and samsungrepo.rc != 90

- name: install required packages
  dnf:
    state: present
    name: "{{ item }}"
  with_items:
    - firefox
    - google-chrome-stable
    - thunderbird
    - evolution
    - sshuttle
    - google-drive-ocamlfuse
    - uld

- name: install required package groups
  dnf:
    state: present
    name: "{{ item }}"
  with_items:
    - "@LibreOffice"

- name: configure firewalld
  firewalld:
    service: uld
    permanent: true
    state: enabled

...
