---

- name: Ensure some base package-groups are installed
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - "@core"
    - "@standard"
    - "@hardware-support"
    - "@base-x"
    - "@firefox"
    - "@fonts"
    - "@libreoffice"
    - "@multimedia"
    - "@networkmanager-submodules"
    - "@printing"
    - "@gnome-desktop"
    - "@development-tools"

- name: Ensure some base packages are installed
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - gnome-keyring-pam
    - vim
    - NetworkManager-openvpn-gnome
    - redshift-gtk
    - nmap
    - tcpdump
    - ansible
    - thunderbird
    - vlc
    - google-chrome-stable
    - android-tools
    - calc
    - gitflow
    - rpmconf
    - strace
    - ffmpeg
    - gvfs-mtp
    - figlet
    - system-config-printer
    - git-review
    - gcc-c++
    - readline-devel
    - gcc-gfortran
    - libX11-devel
    - libXt-devel
    - yum-utils
    - python-firewall.noarch
    - python3-firewall.noarch

- name: Add Google Chrome repository
  yum_repository:
    name: google-chrome
    description: google-chrome
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    enabled: yes
    gpgcheck: yes
    gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub

- name: Add Google Chrome signing key
  rpm_key:
    state: present
    key: https://dl-ssl.google.com/linux/linux_signing_key.pub

# United RPMS are ridiculously broken :-(
# So do not use it any more
#- name: Enable UnitedRPMs for Multimedia
#  dnf:
#    name: https://raw.githubusercontent.com/UnitedRPMs/unitedrpms/master/RPM/unitedrpms-25-1.noarch.rpm
#    state: present
#
#- name: Add UnitedRPMs signing key
#  rpm_key:
#    state: present
#    key: https://raw.githubusercontent.com/UnitedRPMs/unitedrpms.github.io/master/URPMS-GPG-PUBLICKEY-Fedora-24
#    validate_certs: no
#
# Make sure united-RPMS are disabled
#
- name: make sure united RPMS are no longer used
  dnf:
     name: unitedrpms
     state: absent

- name: Install RPM Fusion + RussionFedora NonFree repositories
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
    - http://mirror.yandex.ru/fedora/russianfedora/russianfedora/free/fedora/releases/{{ ansible_distribution_major_version }}/Everything/x86_64/os/russianfedora-free-release-{{ ansible_distribution_major_version }}-1.noarch.rpm
    - http://mirror.yandex.ru/fedora/russianfedora/russianfedora/nonfree/fedora/releases/{{ ansible_distribution_major_version }}/Everything/x86_64/os/russianfedora-nonfree-release-{{ ansible_distribution_major_version }}-1.noarch.rpm
    - http://rpms.famillecollet.com/fedora/{{ ansible_distribution_major_version }}/remi/x86_64/remi-release-{{ ansible_distribution_major_version }}-1.fc27.remi.noarch.rpm

- name: Make sure RPM Fusion directories are enabled
  # YUM Repository module fails
  #  yum_repository:
  #  name: "{{ item }}"
  #  enabled: yes
  shell:
     yum-config-manager --enable {{ item }}
  with_items:
    - rpmfusion-free
    - rpmfusion-free-updates
    - rpmfusion-nonfree
    - rpmfusion-nonfree-updates

#- name: Disable RPM Fusion directories
#  shell: |
#   if cat /etc/yum.repos.d/rpmfusion-*.repo | grep -q "^enabled=1"; then
#     for i in /etc/yum.repos.d/rpmfusion*.repo; do
#       sed -i "s/^enabled=1/enabled=0/g" $i
#       echo "$i disabled"
#     done
#     exit 90
#   else
#     exit 0
#   fi
#  register: disablerepos
#  changed_when: disablerepos == 90
#  failed_when: disablerepos.rc > 0 and disablerepos.rc != 90

- name: Enable copr Repositories for multimedia
  shell: |
   if grep -q "^enabled=1$" "/etc/yum.repos.d/_copr_{{ item.name }}-{{ item.project }}.repo"; then
      exit 90
   else
      dnf -y copr enable "{{ item.name }}/{{ item.project }}"
   fi
  with_items:
    - { name: 'sergiomb', project: 'google-drive-ocamlfuse' }
    - { name: 'mindfulprotons', project: 'atom' }
  register: copr_enabled
  changed_when: copr_enabled.rc == 0
  failed_when: copr_enabled.rc > 0 and copr_enabled.rc != 90
  tags:
    - coprrepo

- name: Enable Samsung ULD repo - ( http://negativo17.org/samsung-unified-linux-driver-printers-scanners/ )
  shell: |
      if [ -f /etc/yum.repos.d/fedora-uld.repo ]; then
         exit 0
      else
         dnf config-manager --add-repo=http://negativo17.org/repos/fedora-uld.repo && exit 90
      fi
  register: samsungrepo
  changed_when: samsungrepo.rc == 90
  failed_when: samsungrepo.rc > 0 and samsungrepo.rc != 90

- name: install required packages
  dnf:
    state: present
    name: "{{ item }}"
  with_items:
    - firefox
    - google-chrome-stable
    - thunderbird
    - evolution
    - sshuttle
    - google-drive-ocamlfuse
    - uld
    - gnome-classic-session
    - xsane
    - gtk-recordmydesktop
    - setroubleshoot
    - policycoreutils-python-utils
    - policycoreutils-gui
    - gnome-tweak-tool

- name: install required package groups
  dnf:
    state: present
    name: "{{ item }}"
  with_items:
    - "@LibreOffice"

- name: configure firewalld
  firewalld:
    service: uld
    permanent: true
    state: enabled

...
