---

- name: Add Google Chrome repository
  yum_repository:
    name: google-chrome
    description: google-chrome
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    enabled: yes
    gpgcheck: yes
    gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub

- name: Add Google Chrome signing key
  rpm_key:
    state: present
    key: https://dl-ssl.google.com/linux/linux_signing_key.pub

- name: Enable UnitedRPMs for Multimedia
  dnf:
    name: https://raw.githubusercontent.com/UnitedRPMs/unitedrpms/master/RPM/unitedrpms-25-1.noarch.rpm
    state: present

- name: Add UnitedRPMs signing key
  rpm_key:
    state: present
    key: https://raw.githubusercontent.com/UnitedRPMs/unitedrpms.github.io/master/URPMS-GPG-PUBLICKEY-Fedora-24
    validate_certs: no

- name: Install RPM Fusion + RussionFedora NonFree repositories
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_lsb.release }}.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_lsb.release }}.noarch.rpm
    - http://mirror.yandex.ru/fedora/russianfedora/russianfedora/free/fedora/releases/25/Everything/x86_64/os/russianfedora-free-release-25-2.noarch.rpm
    - http://mirror.yandex.ru/fedora/russianfedora/russianfedora/nonfree/fedora/releases/25/Everything/x86_64/os/russianfedora-nonfree-release-25-2.noarch.rpm

#- name: Disable RPM Fusion directories
#  yum_repository:
#   name: "{{ item }}"
#   enabled: no
# with_items:
#   - rpmfusion-free
#   - rpmfusion-free-updates
#   - rpmfusion-nonfree
#   - rpmfusion-nonfree-updates

- name: Disable RPM Fusion directories
  shell: |
   if cat /etc/yum.repos.d/rpmfusion-*.repo | grep -q "^enabled=1"; then
     for i in /etc/yum.repos.d/rpmfusion*.repo; do
       sed -i "s/^enabled=1/enabled=0/g" $i
       echo "$i disabled"
     done
     exit 90
   else
     exit 0
   fi
  register: disablerepos
  changed_when: disablerepos == 90
  failed_when: disablerepos.rc > 0 and disablerepos.rc != 90

- name: Enable copr Repositories
  shell: |
   if grep -q "^enabled=1$" "/etc/yum.repos.d/_copr_{{ item.name }}-{{ item.project }}.repo"; then
      exit 90
   else
      dnf -y copr enable "{{ item.name }}/{{ item.project }}"
   fi
  with_items:
    - { name: 'sergiomb', project: 'google-drive-ocamlfuse' }
  register: copr_enabled
  changed_when: copr_enabled.rc == 0
  failed_when: copr_enabled.rc > 0 and copr_enabled.rc != 90
  tags:
    - coprrepo

- name: Disable Samsung ULD repo - is in United ( http://negativo17.org/samsung-unified-linux-driver-printers-scanners/ )
  shell: |
   if [ -f /etc/yum.repos.d/fedora-uld.repo ]; then
      echo ULD repo is enabled, remove it
      rm -f /etc/yum.repos.d/fedora-uld.repo
      exit 90
   else
      echo "Repo is not enabled"
      echo 0
      #dnf config-manager --add-repo=http://negativo17.org/repos/fedora-uld.repo
   fi
  register: samsungrepo
  changed_when: samsungrepo.rc == 90
  failed_when: samsungrepo.rc > 0 and samsungrepo.rc != 90

- name: install required packages
  dnf:
    state: present
    name: "{{ item }}"
  with_items:
    - firefox
    - google-chrome-stable
    - thunderbird
    - evolution
    - sshuttle
    - google-drive-ocamlfuse
    - uld
    - gnome-classic-session
    - xsane
    - gtk-recordmydesktop
    - setroubleshoot
    - policycoreutils-python-utils
    - policycoreutils-gui

- name: install required package groups
  dnf:
    state: present
    name: "{{ item }}"
  with_items:
    - "@LibreOffice"

- name: configure firewalld
  firewalld:
    service: uld
    permanent: true
    state: enabled

...
