---

- name: kernel-development
  dnf:
    state: present
    name: "{{ item }}"
  with_items:
    - fedpkg
    - fedora-packager
    - rpmdevtools
    - ncurses-devel
    - pesign
    - "@developer-workstation-environment"
    - "@development-tools"
    - "@c-development"
    - "@d-development"
    - git
    - rpm-build
    - xxdiff
    - xxdiff-tools
