---

- include: ./base.yml

- include: ./multimedia.yml

- include: ./services.yml

- include: ./system-tuning.yml

- include: ./rhi.yml
  when: not( (rh_internal is undefined) or (rh_internal is none) or (rh_internal | trim == '') )

- include: ./windows.yml
