---

- name: multimedia-packages
  dnf:
    state: present
    name: "{{ item }}"
  with_items:
    - sound-juicer
    - brasero
    - vlc
    - mpv
    - ffmpeg
    - gnome-mpv
    - shotcut
    - obs-studio
    - handbrake-cli
    - handbrake-gui
    - devede
    - deadbeef
    - libdvdcss
    - libdvdnav
    - libdvdread
    - libquicktime
    - faac
    - gstreamer-plugins-ugly
    - gstreamer1-libav
    - gstreamer1-plugins-bad-free
    - gstreamer1-plugins-good
    - gstreamer1-plugins-ugly
    - gstreamer-ffmpeg
    - gstreamer-plugins-bad
    - gstreamer-plugins-bad-free
    - gstreamer-plugins-bad-nonfree
    - gstreamer-plugins-good
    - gstreamer-plugins-ugly
    - gstreamer1-plugins-bad-nonfree
    - shutter
    - vlc
    - libtiff-tools 
    - netpbm-progs
