---

- name: multimedia-packages
  dnf:
    state: present
    name: "{{ item }}"
  with_items:
    - sound-juicer
    - ffmpeg
    - gnome-mpv
    - shotcut
    - devede
    - libdvdnav
    - libdvdread
    - libquicktime
    - faac
    - gstreamer-plugins-ugly
    - gstreamer1-libav
    - gstreamer1-plugins-bad-free
    - gstreamer1-plugins-good
    - gstreamer1-plugins-ugly
    - gstreamer-ffmpeg
    - gstreamer-plugins-bad
    - gstreamer-plugins-bad-free
    - gstreamer-plugins-bad-nonfree
    - gstreamer-plugins-good
    - gstreamer-plugins-ugly
    - gstreamer1-plugins-bad-nonfree
    - shutter
    - vlc
    - libtiff-tools 
    - netpbm-progs
    - lsdvd
    - mplayer
    - mencoder
    - normalize
    - vorbis-tools
    - gpac
    - mkvtoolnix
    - mkvtoolnix-gui
    - libva-intel-driver
    - remmina
    - remmina-plugins-gnome
    - remmina-plugins-spice
    - remmina-plugins-vnc
    - remmina-plugins-rdp.x86_64

## NOTE: libdvdcss is not possible in all countries
##    - libdvdcss
- name: libdvdcss
  dnf:
    state: present
    name: libdvdcss
    enablerepo: remi

