---

- name: check selinux
  selinux: state=enabled

#- name: set ntp server via chrony
#  lineinfile: dest=/etc/chrony.conf line="server {{ ntpserver }} iburst"
#  notify: restart chronyd

#- name: enable chronyd
#  service: name=chronyd state=started enabled=yes

- name: configure firewalld
  firewalld:
    service: uld
    permanent: true
    state: enabled

- name: disable kdump
  service: name=kdump state=stopped enabled=no
  ignore_errors: True

- name: disable abrt
  service: name=abrtd state=stopped enabled=no
  ignore_errors: True

- name: disable abrt-ccpp
  service: name=abrt-ccpp state=stopped enabled=no
  ignore_errors: True

- name: disable numad
  service: name=numad state=stopped enabled=no
  ignore_errors: True

#- name: enable tuned
#  service: name=tuned state=started enabled=yes

...

