---

# Distribute collected hostkeys

# copy local known host to remote host
- name: copy collected ssh hostkeys to remote host
  copy:
    src: ssh_known_hosts
    dest: /etc/ssh/ssh_known_hosts
    owner: root
    group: root
    mode: 0644
  tag:
    - update_ssh_keys
...
